# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{constant-contact-ruby}
  s.version = "0.2.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Craig P Jolicoeur"]
  s.date = %q{2010-03-04}
  s.description = %q{Ruby wrapper around the Constant Contact REST API}
  s.email = %q{cpjolicoeur@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc",
     "TODO"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "TODO",
     "VERSION.yml",
     "constant-contact-ruby.gemspec",
     "lib/constant_contact.rb",
     "lib/constant_contact/activity.rb",
     "lib/constant_contact/base_resource.rb",
     "lib/constant_contact/contact.rb",
     "lib/constant_contact/contact_list.rb",
     "test/fixtures/get_contact.xml",
     "test/fixtures/get_contacts.xml",
     "test/fixtures/post_contacts.xml",
     "test/helper.rb",
     "test/test_constant-contact-ruby.rb",
     "test/test_contacts.rb"
  ]
  s.homepage = %q{http://github.com/cpjolicoeur/constant-contact-ruby}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Constant Contact Ruby API Wrapper}
  s.test_files = [
    "test/helper.rb",
     "test/test_constant-contact-ruby.rb",
     "test/test_contacts.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

